main:
  - name: Home
    url: /
    weight: 1
  - name: python
    url: /python
    weight: 10 
  - name: Data
    url: /Data
    weight: 20
  - name: TiDB
    parent: Data
    url: /Data/TiDB
    weight: 21
  - name: About
    url: about/
    weight: 50
