# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/customization/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    block: navbar
    enable: true
    align: r
    show_logo: true
    # Show a language chooser (if you have translated your site content)?
    show_translations: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} NileCui. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
  show_translations: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  privacy_pack:
    enable: false
  # syntax_highlighter:
  #   theme_light: xcode-light
  #   theme_dark: xcode-dark
  search:
    provider: wowchemy
    wowchemy:
      min_length: 1  # Only the matches whose length exceeds this value will be returned.
      threshold: 0.3  # Where 0 requires a perfect match and 1 matches anything.

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security
security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
